# Generated by Django 2.2.2 on 2019-12-21 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
                ('department_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy_name', models.CharField(max_length=30)),
                ('hierarchy_description', models.TextField(max_length=500)),
                ('hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamWork.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=30)),
                ('org_name', models.CharField(max_length=30)),
                ('org_description', models.TextField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='goalprogress',
            old_name='progress_discription',
            new_name='progress_description',
        ),
        migrations.CreateModel(
            name='OrgRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgRole_name', models.CharField(max_length=30)),
                ('orgRole_description', models.TextField(max_length=500)),
                ('orgRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamWork.Hierarchy')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamWork.Organization'),
        ),
    ]
