# Generated by Django 2.2.5 on 2020-02-19 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWork', '0003_auto_20200219_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamemployee',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamWork.Department'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamWork.TeamEmployee'),
        ),
    ]
