# Generated by Django 2.2.5 on 2020-02-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWork', '0004_auto_20200219_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
