# Generated by Django 2.2.5 on 2020-02-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWork', '0005_remove_team_members'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Permission',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('is_admin', models.BooleanField(default=False)),
        #         ('is_team', models.BooleanField(default=False)),
        #         ('is_user', models.BooleanField(default=True)),
        #     ],
        # ),
        migrations.CreateModel(
            name='TeamAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50)),
                ('member_id', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='department',
        ),
    ]
