# Generated by Django 2.2.5 on 2020-02-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWork', '0011_auto_20200227_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamallocation',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamWork.Employee'),
        ),
        migrations.AlterField(
            model_name='teamallocation',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamWork.Team'),
        ),
    ]
