# Generated by Django 3.0.2 on 2020-03-06 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWork', '0012_auto_20200227_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='help_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='help',
            name='help_topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='help',
            name='help_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='help',
            name='help_discription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
