# Generated by Django 2.2.5 on 2020-03-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWork', '0013_auto_20200309_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualgoal',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualgoal',
            name='is_inprogress',
            field=models.BooleanField(default=True),
        ),
    ]
