# Generated by Django 2.2.5 on 2020-03-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamWork', '0014_auto_20200312_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sup_admin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_team', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=True)),
                ('role_discription', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamWork.RoleEmployee'),
        ),
    ]
